disabled_rules:
  - trailing_whitespace
  - todo
opt_in_rules:
  - empty_count
  - explicit_init
  - force_unwrapping
  - sorted_imports
  - vertical_whitespace_opening_braces
excluded:
  - Pods
  - .build
  - DerivedData
line_length:
  warning: 120
  error: 200
file_length:
  warning: 500
  error: 1200
type_body_length:
  warning: 300
  error: 400
function_body_length:
  warning: 50
  error: 100
cyclomatic_complexity:
  warning: 10
  error: 20
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - x
    - y
    - dx
    - dy
    - r
    - g
    - b
reporter: "xcode"
